### ISSUE TITLE
Mismatch on certain invalid model numbers

### ISSUE THREAD

**Issue by joetennant** [twitter-fabric/apple-model-names#2]
Appears the internal regex is not accounting for the complete "primary number".

Examples:
`getAppleModel('iPhone99,2') --> 'iPhone 7 Plus'`
`getAppleModel('iPhone1234,2') --> 'iPhone 4s'`

This doesn't matter now, but it will in a couple years.

**Comment by joetennant** [comment]
Actually, probably won't be wrong in the future... But, it could be improved.

**Comment by tonybaroneee** [comment]
Thanks for the feedback, Joe! Created https://github.com/twitter-fabric/apple-model-names/pull/3/files to address this.

**Comment by tonybaroneee** [comment]
Version `1.1.0` has been published with this improvement, enjoy!

**Comment by joetennant** [comment]
Awesome. Thanks!
